spring:
  thymeleaf:
    # 关闭thymeleaf缓存 开发时使用 否则没有实时画面
    cache: false
    # 让html标签书写校验不会那么严格
    mode: LEGACYHTML5

db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
  username: root
  password: Abc123D